# Generated by Django 5.0.4 on 2024-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_address_proof_file_student_id_proof_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeshistory',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('library', 'Library'), ('exam', 'Exam'), ('other', 'Other')], max_length=20),
        ),
    ]
