# Generated by Django 5.0.4 on 2024-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_guardian_name_student_guardian_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
